"""Add SpeedProfile and VlanProfile

Revision ID: 01ef63d68226
Revises: b1451364f8c2
Create Date: 2026-05-08 20:12:51.984496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ef63d68226'
down_revision: Union[str, Sequence[str], None] = 'b1451364f8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('download_mbps', sa.Integer(), nullable=True),
    sa.Column('upload_mbps', sa.Integer(), nullable=True),
    sa.Column('upstream_profile', sa.String(), nullable=True),
    sa.Column('downstream_profile', sa.String(), nullable=True),
    sa.Column('uses_gpon_shaping', sa.Boolean(), nullable=True),
    sa.Column('olt_vendor', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speed_profiles_id'), 'speed_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_speed_profiles_name'), 'speed_profiles', ['name'], unique=False)
    op.create_table('vlan_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('site_gateway_id', sa.Integer(), nullable=True),
    sa.Column('allowed_on_uplinks', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlan_profiles_id'), 'vlan_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_vlan_profiles_vlan_id'), 'vlan_profiles', ['vlan_id'], unique=False)
    op.add_column('onu_model_template_matrix', sa.Column('plan_agnostic', sa.Boolean(), nullable=True))
    op.add_column('onu_model_template_matrix', sa.Column('vlan_agnostic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onu_model_template_matrix', 'vlan_agnostic')
    op.drop_column('onu_model_template_matrix', 'plan_agnostic')
    op.drop_index(op.f('ix_vlan_profiles_vlan_id'), table_name='vlan_profiles')
    op.drop_index(op.f('ix_vlan_profiles_id'), table_name='vlan_profiles')
    op.drop_table('vlan_profiles')
    op.drop_index(op.f('ix_speed_profiles_name'), table_name='speed_profiles')
    op.drop_index(op.f('ix_speed_profiles_id'), table_name='speed_profiles')
    op.drop_table('speed_profiles')
    # ### end Alembic commands ###
