"""Initial base migration

Revision ID: 0bb303f4b8e1
Revises: 
Create Date: 2026-05-08 06:18:16.028861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bb303f4b8e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_constraint(op.f('olts_site_gateway_id_fkey'), 'olts', type_='foreignkey')
    op.create_foreign_key(None, 'olts', 'site_gateways', ['site_gateway_id'], ['id'])
    op.drop_index(op.f('ix_onus_sn'), table_name='onus')
    op.create_index(op.f('ix_onus_sn'), 'onus', ['sn'], unique=False)
    op.drop_column('onus', 'pon_port')
    op.drop_column('onus', 'last_sync')
    op.drop_column('onus', 'alias')
    op.drop_column('onus', 'management_ip')
    op.drop_column('onus', 'slot')
    op.drop_column('onus', 'vendor')
    op.drop_column('onus', 'firmware')
    op.drop_column('onus', 'onu_id')
    op.drop_column('onus', 'management_protocol')
    op.alter_column('site_gateways', 'latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_site_gateways_id'), 'site_gateways', ['id'], unique=False)
    op.create_index(op.f('ix_site_gateways_name'), 'site_gateways', ['name'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_site_gateways_name'), table_name='site_gateways')
    op.drop_index(op.f('ix_site_gateways_id'), table_name='site_gateways')
    op.alter_column('site_gateways', 'latency_ms',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('onus', sa.Column('management_protocol', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('onu_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('firmware', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('slot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('management_ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('onus', sa.Column('pon_port', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_onus_sn'), table_name='onus')
    op.create_index(op.f('ix_onus_sn'), 'onus', ['sn'], unique=True)
    op.drop_constraint(None, 'olts', type_='foreignkey')
    op.create_foreign_key(op.f('olts_site_gateway_id_fkey'), 'olts', 'site_gateways', ['site_gateway_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    # ### end Alembic commands ###
