"""Add OnuModelProfile

Revision ID: 586559b45f0e
Revises: 99b2c0d45b3e
Create Date: 2026-05-08 18:00:53.494711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586559b45f0e'
down_revision: Union[str, Sequence[str], None] = '99b2c0d45b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onu_model_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('olt_type_name', sa.String(), nullable=True),
    sa.Column('detected_count', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('source_olt_id', sa.Integer(), nullable=True),
    sa.Column('supports_wifi', sa.Boolean(), nullable=True),
    sa.Column('supports_catv', sa.Boolean(), nullable=True),
    sa.Column('supports_router', sa.Boolean(), nullable=True),
    sa.Column('supports_bridge', sa.Boolean(), nullable=True),
    sa.Column('supports_tr069', sa.Boolean(), nullable=True),
    sa.Column('supports_omci', sa.Boolean(), nullable=True),
    sa.Column('supports_pppoe_router', sa.Boolean(), nullable=True),
    sa.Column('default_line_profile', sa.String(), nullable=True),
    sa.Column('default_service_profile', sa.String(), nullable=True),
    sa.Column('default_tcont_profile', sa.String(), nullable=True),
    sa.Column('default_gemport', sa.String(), nullable=True),
    sa.Column('default_vlan_mode', sa.String(), nullable=True),
    sa.Column('default_eth_mode', sa.String(), nullable=True),
    sa.Column('certification_status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('provisioning_template_id', sa.Integer(), nullable=True),
    sa.Column('config_template_id', sa.Integer(), nullable=True),
    sa.Column('last_extracted_from_onu', sa.String(), nullable=True),
    sa.Column('last_extracted_config', sa.String(), nullable=True),
    sa.Column('last_extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_template_id'], ['provisioning_templates.id'], ),
    sa.ForeignKeyConstraint(['provisioning_template_id'], ['provisioning_templates.id'], ),
    sa.ForeignKeyConstraint(['source_olt_id'], ['olts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onu_model_profiles_id'), 'onu_model_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_onu_model_profiles_model_name'), 'onu_model_profiles', ['model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onu_model_profiles_model_name'), table_name='onu_model_profiles')
    op.drop_index(op.f('ix_onu_model_profiles_id'), table_name='onu_model_profiles')
    op.drop_table('onu_model_profiles')
    # ### end Alembic commands ###
