"""Add OnuConfigAudit and OnuOperationLock

Revision ID: 99b2c0d45b3e
Revises: d66fb7a4919c
Create Date: 2026-05-08 15:38:53.961262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b2c0d45b3e'
down_revision: Union[str, Sequence[str], None] = 'd66fb7a4919c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onu_config_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('onu_interface', sa.String(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=True),
    sa.Column('patch_hash_sha256', sa.String(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('running_config_snapshot', sa.String(), nullable=True),
    sa.Column('generated_patch', sa.JSON(), nullable=True),
    sa.Column('rollback_patch', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('raw_cli_output', sa.String(), nullable=True),
    sa.Column('verification_output', sa.String(), nullable=True),
    sa.Column('rollback_output', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.ForeignKeyConstraint(['onu_id'], ['onus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onu_config_audits_id'), 'onu_config_audits', ['id'], unique=False)
    op.create_index(op.f('ix_onu_config_audits_onu_interface'), 'onu_config_audits', ['onu_interface'], unique=False)
    op.create_table('onu_operation_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onu_id', sa.Integer(), nullable=True),
    sa.Column('olt_id', sa.Integer(), nullable=True),
    sa.Column('onu_interface', sa.String(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('job_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['olt_id'], ['olts.id'], ),
    sa.ForeignKeyConstraint(['onu_id'], ['onus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onu_operation_locks_id'), 'onu_operation_locks', ['id'], unique=False)
    op.create_index(op.f('ix_onu_operation_locks_onu_interface'), 'onu_operation_locks', ['onu_interface'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onu_operation_locks_onu_interface'), table_name='onu_operation_locks')
    op.drop_index(op.f('ix_onu_operation_locks_id'), table_name='onu_operation_locks')
    op.drop_table('onu_operation_locks')
    op.drop_index(op.f('ix_onu_config_audits_onu_interface'), table_name='onu_config_audits')
    op.drop_index(op.f('ix_onu_config_audits_id'), table_name='onu_config_audits')
    op.drop_table('onu_config_audits')
    # ### end Alembic commands ###
