"""Add OnuModelTemplateMatrix

Revision ID: b1451364f8c2
Revises: 586559b45f0e
Create Date: 2026-05-08 18:21:00.854945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1451364f8c2'
down_revision: Union[str, Sequence[str], None] = '586559b45f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onu_model_template_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_profile_id', sa.Integer(), nullable=True),
    sa.Column('provisioning_template_id', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('service_mode', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('upstream_profile', sa.String(), nullable=True),
    sa.Column('downstream_profile', sa.String(), nullable=True),
    sa.Column('vlan_strategy', sa.String(), nullable=True),
    sa.Column('pppoe_mode', sa.String(), nullable=True),
    sa.Column('sample_onu_interface', sa.String(), nullable=True),
    sa.Column('sample_config_snapshot', sa.String(), nullable=True),
    sa.Column('certification_status', sa.String(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.Column('tested_by', sa.String(), nullable=True),
    sa.Column('olt_vendor', sa.String(), nullable=True),
    sa.Column('olt_model', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_profile_id'], ['onu_model_profiles.id'], ),
    sa.ForeignKeyConstraint(['provisioning_template_id'], ['provisioning_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onu_model_template_matrix_id'), 'onu_model_template_matrix', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onu_model_template_matrix_id'), table_name='onu_model_template_matrix')
    op.drop_table('onu_model_template_matrix')
    # ### end Alembic commands ###
