"""Add OnuModelProfile visual fields

Revision ID: c454c7410b06
Revises: 1c0d48d3d525
Create Date: 2026-05-09 05:40:59.920101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c454c7410b06'
down_revision: Union[str, Sequence[str], None] = '1c0d48d3d525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onu_model_profiles', sa.Column('pon_type', sa.String(), nullable=True))
    op.add_column('onu_model_profiles', sa.Column('ethernet_ports', sa.Integer(), nullable=True))
    op.add_column('onu_model_profiles', sa.Column('voip_ports', sa.Integer(), nullable=True))
    op.add_column('onu_model_profiles', sa.Column('wifi_ssids', sa.Integer(), nullable=True))
    op.add_column('onu_model_profiles', sa.Column('service_mode', sa.String(), nullable=True))
    op.add_column('onu_model_profiles', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onu_model_profiles', 'image_url')
    op.drop_column('onu_model_profiles', 'service_mode')
    op.drop_column('onu_model_profiles', 'wifi_ssids')
    op.drop_column('onu_model_profiles', 'voip_ports')
    op.drop_column('onu_model_profiles', 'ethernet_ports')
    op.drop_column('onu_model_profiles', 'pon_type')
    # ### end Alembic commands ###
