"""Add certification fields to ProvisioningTemplate

Revision ID: d66fb7a4919c
Revises: c26edc49784a
Create Date: 2026-05-08 13:41:44.987990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66fb7a4919c'
down_revision: Union[str, Sequence[str], None] = 'c26edc49784a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provisioning_templates', sa.Column('certified', sa.Boolean(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('certified_by', sa.String(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('certified_at', sa.DateTime(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('certification_status', sa.String(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('template_version', sa.Integer(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('source_onu_interface', sa.String(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('source_olt_id', sa.Integer(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('source_running_config', sa.String(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('tested_on_model', sa.String(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('tested_on_firmware', sa.String(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('last_tested_at', sa.DateTime(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('last_test_result', sa.String(), nullable=True))
    op.add_column('provisioning_templates', sa.Column('notes', sa.String(), nullable=True))
    op.create_foreign_key(None, 'provisioning_templates', 'olts', ['source_olt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provisioning_templates', type_='foreignkey')
    op.drop_column('provisioning_templates', 'notes')
    op.drop_column('provisioning_templates', 'last_test_result')
    op.drop_column('provisioning_templates', 'last_tested_at')
    op.drop_column('provisioning_templates', 'tested_on_firmware')
    op.drop_column('provisioning_templates', 'tested_on_model')
    op.drop_column('provisioning_templates', 'source_running_config')
    op.drop_column('provisioning_templates', 'source_olt_id')
    op.drop_column('provisioning_templates', 'source_onu_interface')
    op.drop_column('provisioning_templates', 'template_version')
    op.drop_column('provisioning_templates', 'certification_status')
    op.drop_column('provisioning_templates', 'certified_at')
    op.drop_column('provisioning_templates', 'certified_by')
    op.drop_column('provisioning_templates', 'certified')
    # ### end Alembic commands ###
